/**
 * Tailwind configuration for the Larijani Stone theme.
 *
 * - Colours are driven by CSS custom properties (see src/tailwind.css) so they
 *   can be changed from the Customizer, Elementor Global Colors, or per widget.
 * - Utilities are scoped under `.ls-root` (important selector strategy) so they
 *   win over Elementor's generic rules (e.g. `.elementor img`) without !important.
 * - Preflight is disabled and replaced by a reset scoped to `.ls-root`, so the
 *   theme never breaks Elementor's own widgets or third-party plugins.
 */
const v = (name) => `color-mix(in srgb, var(${name}) calc(<alpha-value> * 100%), transparent)`;

module.exports = {
  content: ['./*.php', './inc/**/*.php', './inc/**/*.html', './woocommerce/**/*.php', './page-templates/**/*.php', './template-parts/**/*.php', './assets/js/**/*.js'],
  important: '.ls-root',
  // Classes built dynamically in PHP (column counts chosen in Elementor).
  safelist: [
    { pattern: /^grid-cols-(1|2|3|4|5|6)$/, variants: ['sm', 'md', 'lg', 'xl'] },
    { pattern: /^col-span-(1|2|3|4|5|6|7|8|9|12)$/, variants: ['lg'] },
  ],
  corePlugins: { preflight: false },
  theme: {
    extend: {
      maxWidth: { '7xl': 'var(--ls-container, 80rem)' },
      colors: {
        // Brand palette (variable driven).
        brand: {
          DEFAULT: v('--ls-primary'),
          sage: v('--ls-primary'),
          sageHover: v('--ls-primary-hover'),
          dark: v('--ls-dark'),
          surface: v('--ls-canvas'),
          border: v('--ls-border'),
          light: v('--ls-secondary'),
        },
        'primary-container': v('--ls-primary'),
        primary: v('--ls-primary-hover'),
        'surface-dark': v('--ls-dark'),
        'surface-footer': v('--ls-footer'),
        'surface-canvas': v('--ls-canvas'),
        'border-subtle': v('--ls-border'),
        'brand-secondary': v('--ls-secondary'),
        // Static design tokens from the "Larijani Stone Industrial" design system.
        'surface-card': '#FFFFFF',
        surface: '#f9f9ff',
        'surface-dim': '#d0daf0',
        'surface-bright': '#f9f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f3ff',
        'surface-container': '#e7eeff',
        'surface-container-high': '#dee8ff',
        'surface-container-highest': '#d9e3f9',
        'surface-variant': '#d9e3f9',
        'on-surface': '#121c2c',
        'on-surface-variant': '#454841',
        'inverse-surface': '#273141',
        'inverse-on-surface': '#ebf1ff',
        'inverse-primary': '#bfcab3',
        outline: '#686B63',
        'outline-variant': '#c5c7be',
        'surface-tint': '#57624f',
        'on-primary': '#ffffff',
        'on-primary-container': '#d9e5cd',
        secondary: '#51634a',
        'on-secondary': '#ffffff',
        'secondary-container': '#d4e9c8',
        'on-secondary-container': '#576a50',
        tertiary: '#464d49',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#5e6561',
        'on-tertiary-container': '#dbe2dd',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#dbe6cf',
        'primary-fixed-dim': '#bfcab3',
        'on-primary-fixed': '#151e10',
        'on-primary-fixed-variant': '#3f4a38',
        'secondary-fixed': '#d4e9c8',
        'secondary-fixed-dim': '#b8cdae',
        'on-secondary-fixed': '#0f1f0b',
        'on-secondary-fixed-variant': '#3a4b34',
        'tertiary-fixed': '#dde4df',
        'tertiary-fixed-dim': '#c1c8c3',
        'on-tertiary-fixed': '#161d1a',
        'on-tertiary-fixed-variant': '#414845',
        background: '#f9f9ff',
        'on-background': '#121c2c',
        'accent-emerald': '#047857',
        'accent-amber': '#92400E',
        'accent-cobalt': '#1E40AF',
      },
      fontFamily: {
        sans: ['var(--ls-font)'],
        'display-hero': ['var(--ls-font)'],
        'display-hero-mobile': ['var(--ls-font)'],
        'headline-lg': ['var(--ls-font)'],
        'headline-md': ['var(--ls-font)'],
        'headline-sm': ['var(--ls-font)'],
        'title-card': ['var(--ls-font)'],
        'body-lg': ['var(--ls-font)'],
        'body-md': ['var(--ls-font)'],
        'body-sm': ['var(--ls-font)'],
        'label-badge': ['var(--ls-font)'],
        'label-nav': ['var(--ls-font)'],
      },
      fontSize: {
        'display-hero': ['calc(3rem * var(--ls-fs-h, 1) * var(--ls-fs-r, 1))', { lineHeight: '1.25', fontWeight: '900' }],
        'display-hero-mobile': ['calc(1.75rem * var(--ls-fs-h, 1) * var(--ls-fs-r, 1))', { lineHeight: '1.3', fontWeight: '900' }],
        'headline-lg': ['calc(1.875rem * var(--ls-fs-h, 1) * var(--ls-fs-r, 1))', { lineHeight: '1.3', fontWeight: '900' }],
        'headline-md': ['calc(1.5rem * var(--ls-fs-h, 1) * var(--ls-fs-r, 1))', { lineHeight: '1.35', fontWeight: '800' }],
        'headline-sm': ['calc(1.125rem * var(--ls-fs-h, 1) * var(--ls-fs-r, 1))', { lineHeight: '1.4', fontWeight: '800' }],
        'title-card': ['calc(1rem * var(--ls-fs-h, 1) * var(--ls-fs-r, 1))', { lineHeight: '1.4', fontWeight: '800' }],
        'body-lg': ['calc(1rem * var(--ls-fs-b, 1) * var(--ls-fs-r, 1))', { lineHeight: '1.65', fontWeight: '400' }],
        'body-md': ['calc(0.875rem * var(--ls-fs-b, 1) * var(--ls-fs-r, 1))', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['calc(0.75rem * var(--ls-fs-b, 1) * var(--ls-fs-r, 1))', { lineHeight: '1.5', fontWeight: '400' }],
        'label-badge': ['calc(0.6875rem * var(--ls-fs-b, 1) * var(--ls-fs-r, 1))', { lineHeight: '1', fontWeight: '700' }],
        'label-nav': ['calc(0.875rem * var(--ls-fs-b, 1) * var(--ls-fs-r, 1))', { lineHeight: '1.25', fontWeight: '600' }],
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        'space-2xl': '4rem',
        gutter: '1.5rem',
        'gutter-mobile': '0.75rem',
        margin: '2rem',
        'margin-mobile': '1rem',
        13: '3.25rem',
        18: '4.5rem',
      },
      boxShadow: {
        soft: '0 8px 30px rgba(0, 0, 0, 0.05)',
        floating: '0 20px 40px rgba(45, 56, 42, 0.08)',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')({ strategy: 'class' }), require('@tailwindcss/container-queries')],
};
