<?php
/**
 * Demo content shared by widget defaults and the demo importer.
 *
 * @package Larijani
 */

defined( 'ABSPATH' ) || exit;

/**
 * Portfolio projects from the design.
 *
 * @return array
 */
function ls_demo_projects() {
	return array(
		array( 'image' => 'project_1', 'filter' => 'facade', 'badge_1' => 'قالب پلیمر ABS نشکن', 'badge_2' => 'سنگ دکوراتیو ۳D', 'badge_2_tone' => 'dark', 'location' => 'تهران، برج اداری پارک‌وی', 'code' => 'کد قالب: ۳D-904', 'title' => 'نمای صخره‌ای و تاشو هندسی برج اداری', 'desc' => 'اجرای بیش از ۸۵۰ مترمربع پنل بتنی فوق سبک سه‌بعدی با زاویه‌های شکست نور شارپ. تولید شده با رزین پلی‌کربوکسیلات مقاوم و عاری از هرگونه حباب هوا.', 'spec1_label' => 'ابعاد تایل', 'spec1_value' => '۵۰×۵۰ سانتیمتر', 'spec2_label' => 'فرمول ترکیب', 'spec2_value' => 'ژل میکروسیلیس', 'spec3_label' => 'تراکم ارتعاش', 'spec3_value' => '۳۵۰۰ دور/دقیقه', 'note' => 'فاقد تغییر رنگ در تابش UV', 'note_icon' => 'patch-check-fill', 'note_tone' => 'emerald' ),
		array( 'image' => 'project_2', 'filter' => 'paving', 'badge_1' => 'واش‌بتن آنتی‌اسلیپ', 'badge_2' => 'سنگدانه مرمر الیگودرز', 'badge_2_tone' => 'sage', 'location' => 'لواسان، شهرک ویلایی سرو', 'code' => 'کد قالب: WB-4040', 'title' => 'محوطه‌سازی و کفسازی ویلای مدرن لواسان', 'desc' => 'تولید ۱,۴۰۰ مترمربع تایل واش‌بتن شیاردار با تکنولوژی ارتعاش فشرده لاریجانی استون، مقاومت یخبندان تا ۳۵ دوره سرمای شدید بدون پوسته‌شدن.', 'spec1_label' => 'ضخامت قطعه', 'spec1_value' => '۳.۵ سانتیمتر', 'spec2_label' => 'رزین مصرفی', 'spec2_value' => 'کربوکسیلات کد ۶۰', 'spec3_label' => 'مقاومت فشاری', 'spec3_value' => '۴۸ مگاپاسکال', 'note' => 'جذب آب زیر ۳ درصد', 'note_icon' => 'droplet-fill', 'note_tone' => 'muted' ),
		array( 'image' => 'project_3', 'filter' => 'landscape', 'badge_1' => 'جدول و دورباغچه هلالی', 'badge_2' => 'قالب تزریق یکپارچه', 'badge_2_tone' => 'primary', 'location' => 'کرج، بوستان تفریحی البرز', 'code' => 'کد: JDL-112', 'title' => 'جدول‌گذاری مدرن و دورباغچه پارک شهری البرز', 'desc' => 'تولید بیش از ۴,۵۰۰ شاخه جدول پلیمری ۵۰ سانتیمتری با قالب‌های نشکن لاریجانی استون، جایگزین کامل جداول سنتی پرحباب شهرداری با دوام ۳ برابری.', 'spec1_label' => 'طول شاخه', 'spec1_value' => '۵۰ سانتیمتر', 'spec2_label' => 'سطح نهایی', 'spec2_value' => 'صیقلی خودرنگ', 'spec3_label' => 'مقاومت نمک', 'spec3_value' => 'کامپوزیت ضدسولفات', 'note' => 'بدون نیاز به رنگ‌آمیزی سالانه', 'note_icon' => 'tree-fill', 'note_tone' => 'emerald' ),
		array( 'image' => 'project_4', 'filter' => 'facade', 'badge_1' => 'ستون، سرستون و کتیبه', 'badge_2' => 'قالب فایبرگلاس صنعتی', 'badge_2_tone' => 'fixed', 'location' => 'مازندران، متل‌قو (برج ساحلی)', 'code' => 'کد: CLM-80', 'title' => 'نمای کلاسیک برج ساحلی با صراحی و سرستون', 'desc' => 'قالب‌گیری فوق‌دقیق نقوش با فایبرگلاس چندلایه و بتن الیافی مسلح (GFRC)، مقاوم در برابر رطوبت ۱۰۰ درصدی ساحلی بدون شوره یا ریزش سنگ.', 'spec1_label' => 'قطر ستون', 'spec1_value' => '۴۰ سانتیمتر', 'spec2_label' => 'نوع الیاف', 'spec2_value' => 'پلی‌پروپیلن ۱۲mm', 'spec3_label' => 'وزن نهایی', 'spec3_value' => '۴۰٪ سبک‌تر از تراورتن', 'note' => 'ضمانت مادام‌العمر چسبندگی', 'note_icon' => 'shield-fill-check', 'note_tone' => 'muted' ),
		array( 'image' => 'project_5', 'filter' => 'industrial', 'badge_1' => 'تجهیز خط تولید کامل', 'badge_2' => 'میز ویبره + پان میکسر', 'badge_2_tone' => 'primary', 'location' => 'تبریز، شهرک صنعتی سلیمی', 'code' => 'ظرفیت: ۴۰۰متر/روز', 'title' => 'راه‌اندازی صفر تا صد کارخانه سنگ پلیمری ارس', 'desc' => 'طراحی و ساخت ۲ دستگاه میز ویبره ۳ متری دوموتوره متغیر، میکسر ۳۵۰ لیتری طرح آلمان، تأمین ۸۰۰ عدد قالب کفپوش و نما و آموزش تخصصی فرآوری.', 'spec1_label' => 'الکتروموتور', 'spec1_value' => 'موتوجن تبریز ۵.۵ اسب', 'spec2_label' => 'ورق کفی میز', 'spec2_value' => '۸ میلی‌متر ST-37', 'spec3_label' => 'بازدهی خط', 'spec3_value' => '۳۸۰ مترمربع در شیفت', 'note' => 'گارانتی طلایی ۱۸ ماهه ماشین‌آلات', 'note_icon' => 'award-fill', 'note_tone' => 'emerald' ),
		array( 'image' => 'project_6', 'filter' => 'paving', 'badge_1' => 'کفپوش بتنی ترافیکی سنگین', 'badge_2' => 'تحمل بار ۶۰ تن', 'badge_2_tone' => 'dark', 'location' => 'اصفهان، مجتمع فولاد زاگرس', 'code' => 'کد: HVY-6060', 'title' => 'کفسازی صنعتی سوله فرآوری فولاد زاگرس', 'desc' => 'اجرای تایل‌های ۶۰×۶۰ مسلح به پودر سخت‌کننده کروندوم و روان‌ساز پلیمری با فرمولاسیون لاریجانی استون، کاملاً ضد گردوغبار تحت سایش مداوم لیفتراک‌های سنگین.', 'spec1_label' => 'ضخامت تایل', 'spec1_value' => '۵ سانتیمتر مسلح', 'spec2_label' => 'سختی سطح', 'spec2_value' => '۷ در مقیاس موهس', 'spec3_label' => 'تحمل نقطه‌ای', 'spec3_value' => '۶۵۰ کیلوگرم/سانتی‌متر', 'note' => 'مقاومت سایشی کلاس ۱ صنعتی', 'note_icon' => 'truck', 'note_tone' => 'muted' ),
	);
}

/**
 * Catalog products from the design (shop page).
 *
 * @return array
 */
function ls_demo_catalog() {
	return array(
		array( 'image' => 'catalog_1', 'filter' => 'mold', 'badge' => 'تزریق ABS نشکن', 'badge_tone' => 'light', 'code' => 'کد: LS-M102', 'title' => 'قالب سنگ پلیمری طرح سه‌بعدی کریستالی و صخره‌ای', 'desc' => 'ورق ضخامت ۴ میل خالص، بدون لچکی و تغییر زاویه در بیش از ۱۰۰ بار ویبره بتن خودتراکم.', 'spec1_label' => 'ابعاد', 'spec1_value' => '۳۰×۵۰ سانت', 'spec2_label' => 'ضخامت', 'spec2_value' => '۴ میلی‌متر', 'spec3_label' => 'جدایش قطعه', 'spec3_value' => 'بدون اسید', 'price_label' => 'قیمت واحد', 'price' => '۱۲۵,۰۰۰', 'price_raw' => 125000, 'button_text' => 'خرید قالب', 'button_icon' => 'cart-plus-fill', 'chat_button' => 'yes' ),
		array( 'image' => 'catalog_2', 'filter' => 'machinery', 'badge' => 'گارانتی ۲۴ ماهه', 'badge_tone' => 'amber', 'code' => 'کد: LS-VT200', 'title' => 'میز ویبره صنعتی دور متغیر لاریجانی استون', 'desc' => 'دارای ۲ موتور ارتعاشی وارداتی ایتالیایی، ورق رویه ۸ میلی‌متر، شاسی تیرآهن ۱۴ دوبل ضد تاب‌برداشتن.', 'spec1_label' => 'ابعاد میز', 'spec1_value' => '۲×۱ متر', 'spec2_label' => 'ظرفیت بار', 'spec2_value' => '۸۰۰ کیلو', 'spec3_label' => 'اینورتر', 'spec3_value' => 'دارد (LS کره)', 'price_label' => 'قیمت مصوب', 'price' => '۴۸,۰۰۰,۰۰۰', 'price_raw' => 48000000, 'button_text' => 'سفارش مستقیم', 'button_style' => 'dark', 'button_icon' => 'telephone-outbound-fill', 'button_link' => 'tel:09122302685' ),
		array( 'image' => 'catalog_3', 'filter' => 'mold', 'badge' => 'پرفروش‌ترین قالب کف', 'badge_tone' => 'primary', 'code' => 'کد: LS-P404', 'title' => 'قالب کفپوش واش‌بتن ۴۰×۴۰ طرح شیاردار ضدلغزش', 'desc' => 'تولید شده از گرانول ABS نو مقاوم به فشار پرس هیدرولیک و ارتعاش پیوسته بدون ترک خوردگی.', 'spec1_label' => 'ابعاد قطعه', 'spec1_value' => '۴۰×۴۰ سانت', 'spec2_label' => 'ضخامت نهایی', 'spec2_value' => '۳.۵ سانت', 'spec3_label' => 'زاویه خروج', 'spec3_value' => 'استاندارد ۳°', 'price_label' => 'قیمت واحد', 'price' => '۱۱۰,۰۰۰', 'price_raw' => 110000, 'button_text' => 'ثبت سفارش', 'button_icon' => 'cart-plus-fill' ),
		array( 'image' => 'catalog_4', 'filter' => 'chemical', 'badge' => 'پلی‌کربوکسیلات اتر', 'badge_tone' => 'light', 'code' => 'کد: LS-SP300', 'title' => 'فوق‌روان‌کننده کربوکسیلاتی اختصاصی سنگ مصنوعی', 'desc' => 'گالن ۲۰ لیتری روان‌کننده با کاهش ۳۰ درصدی نسبت آب به سیمان و رساندن مقاومت فشاری به ۶۰ مگاپاسکال.', 'spec1_label' => 'حجم بسته', 'spec1_value' => '۲۰ لیتر خالص', 'spec2_label' => 'دوز مصرف', 'spec2_value' => '۰.۸٪ تا ۱.۲٪', 'spec3_label' => 'ویژگی بارز', 'spec3_value' => 'سطح آینه‌ای', 'price_label' => 'قیمت هر گالن', 'price' => '۱,۴۵۰,۰۰۰', 'price_raw' => 1450000, 'button_text' => 'خرید گالن', 'button_icon' => 'cart-plus-fill' ),
		array( 'image' => 'catalog_5', 'filter' => 'machinery', 'badge' => 'موتور ۱۰ اسب موتوژن', 'badge_tone' => 'light', 'code' => 'کد: LS-MX500', 'title' => 'میکسر ۵۰۰ کیلویی طرح پان بتن پلیمری و سنگ مهندسی', 'desc' => 'کف و جداره ورق ۱۰ میلیمتر ضدسایش ST52، بازوهای گریز از مرکز فنردار و گیربکس سهند شافت درشت.', 'spec1_label' => 'ظرفیت بار', 'spec1_value' => '۵۰۰ کیلوگرم', 'spec2_label' => 'ضخامت ورق', 'spec2_value' => '۱۰ میل ST52', 'spec3_label' => 'دریچه خروج', 'spec3_value' => 'پنوماتیک', 'price_label' => 'قیمت دستگاه', 'price' => '۹۲,۰۰۰,۰۰۰', 'price_raw' => 92000000, 'button_text' => 'سفارش ساخت', 'button_style' => 'dark', 'button_icon' => 'telephone-outbound-fill', 'button_link' => 'tel:09122302685' ),
		array( 'image' => 'catalog_6', 'filter' => 'mold', 'badge' => 'قالب دورباغچه ABS', 'badge_tone' => 'light', 'code' => 'کد: LS-C503', 'title' => 'قالب جدول و دورباغچه فانتزی مدل سنتی و مدرن', 'desc' => 'ابعاد ۵۰×۳۰ سانتیمتر با لبه‌های کونیک جهت جدایش روان سنگ از قالب در کمتر از ۳ ثانیه.', 'spec1_label' => 'طول جدول', 'spec1_value' => '۵۰ سانتیمتر', 'spec2_label' => 'ارتفاع', 'spec2_value' => '۳۰ سانتیمتر', 'spec3_label' => 'ضخامت ورق', 'spec3_value' => '۴ میلی‌متر', 'price_label' => 'قیمت واحد', 'price' => '۸۵,۰۰۰', 'price_raw' => 85000, 'button_text' => 'خرید قالب', 'button_icon' => 'cart-plus-fill' ),
		array( 'image' => 'catalog_7', 'filter' => 'chemical', 'badge' => 'بایفروکس آلمان', 'badge_tone' => 'amber', 'code' => 'کد: LS-PG130', 'title' => 'رنگدانه معدنی اکسید آهن قرمز و اخرایی (Bayferrox)', 'desc' => 'کیسه ۲۵ کیلوگرمی پودر معدنی ضد اشعه ماوراءبنفش آفتاب بدون محو شدن یا تغییر فاز رنگ در طول ۱۰ سال.', 'spec1_label' => 'وزن کیسه', 'spec1_value' => '۲۵ کیلوگرم', 'spec2_label' => 'پایداری UV', 'spec2_value' => 'گرید A آلمان', 'spec3_label' => 'پوشش‌دهی', 'spec3_value' => 'فوق‌العاده', 'price_label' => 'قیمت هر کیسه', 'price' => '۳,۸۰۰,۰۰۰', 'price_raw' => 3800000, 'button_text' => 'خرید کیسه', 'button_icon' => 'cart-plus-fill' ),
		array( 'image' => 'catalog_8', 'filter' => 'mold', 'badge' => 'فایبرگلاس دوتکه', 'badge_tone' => 'light', 'code' => 'کد: LS-SR70', 'title' => 'قالب صراحی گرد رومی ۷۰ سانتی فایبرگلاس نشکن', 'desc' => 'دارای شاسی و پیچ‌ومهره‌های قفل‌شونده سریع جهت مهار فشار بتن، خروجی سطح صیقلی سنگ مهندسی.', 'spec1_label' => 'ارتفاع ستون', 'spec1_value' => '۷۰ سانتیمتر', 'spec2_label' => 'ساختار قالب', 'spec2_value' => 'دو پارچه پیچ‌دار', 'spec3_label' => 'عمر مفید', 'spec3_value' => '۳۰۰ مرتبه', 'price_label' => 'قیمت هر دست', 'price' => '۲۹۰,۰۰۰', 'price_raw' => 290000, 'button_text' => 'خرید دست', 'button_icon' => 'cart-plus-fill' ),
	);
}

/**
 * Cross-sell cards (single product page).
 *
 * @return array
 */
function ls_demo_cross_sell() {
	return array(
		array( 'image' => 'cross_1', 'badge' => 'گالن ۲۰ لیتری', 'title' => 'فوق‌روان‌کننده پلی‌کربوکسیلات نانو (LS-500)', 'desc' => 'کاهش ۳۰ درصدی آب مصرفی، افزایش مقاومت فشاری تا ۷۵ مگاپاسکال و روان‌سازی کامل گوشه‌های تیز قالب.', 'price_label' => 'قیمت هر گالن:', 'price' => '۱,۶۵۰,۰۰۰', 'button_icon' => 'cart-plus' ),
		array( 'image' => 'cross_2', 'badge' => 'آب‌گریز ضدشوره', 'title' => 'رزین سیلر براق‌کننده و نانو محافظ سنگ نما', 'desc' => 'ایجاد لایه خودتمیزشونده و جلوه خیس (Wet Look) دائمی در برابر اشعه UV آفتاب بدون زردشدگی.', 'price_label' => 'قیمت ظرف ۴ لیتری:', 'price' => '۸۸۰,۰۰۰', 'button_icon' => 'cart-plus' ),
		array( 'image' => 'cross_3', 'badge' => 'کیسه ۲۵ کیلویی', 'title' => 'رنگ معدنی اکسید آهن بایفروکس آلمان (مشکی ۳۳۰)', 'desc' => 'بالاترین قدرت رنگ‌دهی و ثبات نوری بدون رنگ‌پریدگی، ویژه ساخت سنگ‌های بازالتی دکوراتیو لوکس.', 'price_label' => 'قیمت هر کیلو:', 'price' => '۲۴۵,۰۰۰', 'button_icon' => 'cart-plus' ),
		array( 'image' => 'cross_4', 'badge' => 'ابعاد ۲×۱ متر', 'title' => 'میز ویبره صنعتی دوموتوره ارتعاش عمودی', 'desc' => 'طراحی اختصاصی با ورق ضخیم ۸ میلی‌متر و فنرهای فولادی جهت تراکم کامل سنگ‌های سه‌بعدی بدون شکست قالب.', 'price_label' => 'قیمت کارخانه:', 'price' => '۴۸,۰۰۰,۰۰۰', 'button_icon' => 'telephone', 'button_link' => 'tel:09122302685' ),
	);
}

/**
 * Products of the full-width shop design (screen _2).
 *
 * @return array
 */
function ls_demo_store_items() {
	return array(
		array( 'image' => 'store_1', 'badge' => 'گارانتی ۲۴ ماهه', 'badge_tone' => 'dark', 'stock_badge' => 'موجود در کارخانه', 'stock_tone' => 'emerald', 'category' => 'تجهیزات خط تولید • ماشین‌آلات', 'title' => 'میز ویبره صنعتی دور متغیر لاریجانی استون', 'desc' => 'دارای ۲ عدد الکتروموتور ۳۰۰۰ دور ایتالیایی، صفحه ورق ۸ میل ضدرنگ، فنرهای لول ارتعاشی سایلنت جهت خروج ۱۰۰٪ حباب‌های هوا.', 'spec1_label' => 'ابعاد صفحه', 'spec1_value' => '۲۰۰×۱۰۰ سانتی‌متر', 'spec2_label' => 'سیستم لرزش', 'spec2_value' => 'فرکانس متغیر اینورتری', 'spec3_label' => 'ظرفیت بار', 'spec3_value' => '۸۰۰ کیلوگرم', 'price_label' => 'قیمت کارخانه:', 'price' => '۴۸,۰۰۰,۰۰۰', 'price_raw' => 48000000, 'button_text' => 'سفارش مستقیم و هماهنگی ارسال', 'button_icon' => 'cart-check', 'button_link' => 'tel:09122302685', 'filter' => 'machinery ready-stock' ),
		array( 'image' => 'store_2', 'badge' => 'طرح سه‌بعدی لوکس (تصویر شاخص)', 'badge_tone' => 'amber', 'stock_badge' => 'قالب تزریق ABS', 'stock_tone' => 'dark', 'category' => 'قالب‌های نما و دکوراتیو • دیواری', 'title' => 'قالب سنگ پلیمری طرح سه‌بعدی کریستالی و صخره‌ای', 'desc' => 'قالب فوق‌دقیق ژئومتریک پلیمری با زاویه‌های شکسته نوری جهت خلق نمای مدرن داخلی و ویلایی با رهایش آسان و بدون چسبندگی.', 'spec1_label' => 'ابعاد تایل', 'spec1_value' => '۵۰×۳۰ سانتی‌متر', 'spec2_label' => 'ضخامت قالب', 'spec2_value' => '۴ میلی‌متر نو', 'spec3_label' => 'تعداد شات', 'spec3_value' => '+۵۰۰ بار تولید', 'price_label' => 'قیمت هر عدد قالب:', 'price' => '۱۳۵,۰۰۰', 'price_raw' => 135000, 'button_text' => 'خرید تعدادی و عمده قالب', 'button_icon' => 'cart-plus', 'button_link' => 'tel:09354431321', 'filter' => 'molds ready-stock' ),
		array( 'image' => 'store_3', 'badge' => 'پرفروش‌ترین قالب کف', 'badge_tone' => 'sage', 'stock_badge' => '', 'stock_tone' => 'dark', 'category' => 'قالب‌های کفپوش و محوطه • ABS', 'title' => 'قالب کفپوش واش‌بتن ۴۰×۴۰ طرح شیاردار ضدلغزش', 'desc' => 'تولید شده از گرانول ABS نو با مقاومت کششی بالا و دیواره‌های تقویت‌شده لبه‌دار، بدون دفورمه شدن در فصول گرم و سرد سال.', 'spec1_label' => 'ابعاد دقیق', 'spec1_value' => '۴۰×۴۰ سانت', 'spec2_label' => 'ضخامت سنگ', 'spec2_value' => '۳.۵ سانتی‌متر', 'spec3_label' => 'متریال', 'spec3_value' => 'ABS نشکن عیار A', 'price_label' => 'قیمت هر عدد:', 'price' => '۱۱۰,۰۰۰', 'price_raw' => 110000, 'button_text' => 'خرید قالب کفپوش', 'button_icon' => 'cart-plus', 'button_link' => 'tel:09354431321', 'filter' => 'molds ready-stock' ),
		array( 'image' => 'store_4', 'badge' => 'اصلاح‌کننده بتن گرید A+', 'badge_tone' => 'emerald', 'stock_badge' => '', 'stock_tone' => 'dark', 'category' => 'مواد اولیه تخصصی • شیمی بتن', 'title' => 'فوق‌روان‌کننده کربوکسیلاتی اختصاصی سنگ مصنوعی', 'desc' => 'افزایش مقاومت فشاری تا ۳۵ مگاپاسکال، کاهش چشمگیر نسبت آب به سیمان، ایجاد براقیت سطحی و خودتراکمی ملات بدون افت اسلامپ.', 'spec1_label' => 'بسته‌بندی', 'spec1_value' => 'گالن ۲۰ لیتری', 'spec2_label' => 'میزان مصرف', 'spec2_value' => '۰.۶٪ وزن سیمان', 'spec3_label' => 'پایه فرمول', 'spec3_value' => 'پلی‌کربوکسیلات اتر', 'price_label' => 'قیمت گالن ۲۰ لیتری:', 'price' => '۱,۴۵۰,۰۰۰', 'price_raw' => 1450000, 'button_text' => 'سفارش رزین و تست کارگاهی', 'button_icon' => 'eyedropper', 'button_link' => 'tel:09354431321', 'filter' => 'materials ready-stock' ),
		array( 'image' => 'store_5', 'badge' => 'تیغه‌های ضدسایش هاردوکس', 'badge_tone' => 'dark', 'stock_badge' => '', 'stock_tone' => 'dark', 'category' => 'ماشین‌آلات تخصصی • همزن صنعتی', 'title' => 'میکسر ۵۰۰ کیلویی طرح پان بتن پلیمری و سنگ مهندسی', 'desc' => 'میکسر خورشیدی با گیربکس تقویت‌شده روسی، اختلاط یکدست الیاف پلی‌پروپیلن و رزین بدون ایجاد گلوله سیمانی، با تخلیه پنوماتیک تحتانی.', 'spec1_label' => 'توان موتور', 'spec1_value' => '۱۰ اسب موتوژن', 'spec2_label' => 'حجم بارگیری', 'spec2_value' => '۵۰۰ کیلوگرم', 'spec3_label' => 'ضخامت دیواره', 'spec3_value' => '۱۰ میلیمتر ST52', 'price_label' => 'قیمت نهایی دستگاه:', 'price' => '۹۲,۰۰۰,۰۰۰', 'price_raw' => 92000000, 'button_text' => 'سفارش ساخت سفارشی میکسر', 'button_icon' => 'gear', 'button_link' => 'tel:09122302685', 'filter' => 'machinery' ),
		array( 'image' => 'store_6', 'badge' => 'دو تکه با پین تراز', 'badge_tone' => 'dark', 'stock_badge' => '', 'stock_tone' => 'dark', 'category' => 'قالب‌های نرده و صراحی • نما رومی', 'title' => 'قالب صراحی گرد رومی ۷۰ سانتی فایبرگلاس نشکن', 'desc' => 'مناسب تولید نرده تراس و محوطه ویلایی با خط درز نامرئی، مقاومت ضربه‌ای بسیار بالا و قابلیت مسلح‌سازی با میلگرد سایز ۸.', 'spec1_label' => 'ارتفاع', 'spec1_value' => '۷۰ سانتی‌متر', 'spec2_label' => 'جنس قالب', 'spec2_value' => 'کامپوزیت پلیمری', 'spec3_label' => 'سیستم بست', 'spec3_value' => 'پیچ و گیره فلزی', 'price_label' => 'قیمت هر دست کامل:', 'price' => '۲۹۰,۰۰۰', 'price_raw' => 290000, 'button_text' => 'خرید قالب صراحی', 'button_icon' => 'cart-plus', 'button_link' => 'tel:09354431321', 'filter' => 'molds ready-stock' ),
		array( 'image' => 'store_7', 'badge' => 'ابعاد ۵۰×۳۰ سانت', 'badge_tone' => 'sage', 'stock_badge' => '', 'stock_tone' => 'dark', 'category' => 'قالب‌های محوطه • دورباغچه و جدول', 'title' => 'قالب جدول و دورباغچه فانتزی مدل سنتی و مدرن', 'desc' => 'سطح صیقلی بدون نیاز به اسیدشویی، خارج‌سازی سریع قطعه از قالب در کمتر از ۲۴ ساعت، مقاوم در برابر سایش سیمان و شن نخودی.', 'spec1_label' => 'طول قطعه', 'spec1_value' => '۵۰ سانتی‌متر', 'spec2_label' => 'ارتفاع', 'spec2_value' => '۳۰ سانتی‌متر', 'spec3_label' => 'متریال', 'spec3_value' => 'ABS کره مقاوم', 'price_label' => 'قیمت هر قالب:', 'price' => '۸۵,۰۰۰', 'price_raw' => 85000, 'button_text' => 'خرید قالب دورباغچه', 'button_icon' => 'cart-plus', 'button_link' => 'tel:09354431321', 'filter' => 'molds ready-stock' ),
		array( 'image' => 'store_8', 'badge' => 'مقاوم به اشعه UV خورشید', 'badge_tone' => 'dark', 'stock_badge' => '', 'stock_tone' => 'dark', 'category' => 'رنگ و افزودنی‌ها • پیگمنت بایفروکس', 'title' => 'رنگدانه معدنی اکسید آهن قرمز، اخرایی و مشکی آلمانی', 'desc' => 'پیگمنت پودری میکرونیزه وارداتی ضدبورشدگی در مقابل نور آفتاب، بدون تداخل با گیرش اولیه سیمان سفید و سیاه، کیسه اورجینال ۲۵ کیلویی.', 'spec1_label' => 'وزن کیسه', 'spec1_value' => '۲۵ کیلوگرم خالص', 'spec2_label' => 'پایداری نوری', 'spec2_value' => 'گرید ۸ و ۱۰ صنعتی', 'spec3_label' => 'کشور مبدأ', 'spec3_value' => 'آلمان (Bayferrox)', 'price_label' => 'قیمت هر کیسه ۲۵ کیلویی:', 'price' => '۳,۸۰۰,۰۰۰', 'price_raw' => 3800000, 'button_text' => 'استعلام کالیته رنگ و سفارش', 'button_icon' => 'palette', 'button_link' => 'tel:09354431321', 'filter' => 'materials ready-stock' ),
	);
}
