<?php
/** Capability-checked import, export and reset handlers. */
defined('ABSPATH') || exit;
function frpmt_transfer(){if(!current_user_can('edit_theme_options'))wp_die(esc_html__('دسترسی مجاز نیست.','frpmesh-hybrid'));check_admin_referer('frpmt_transfer');$status='';if(isset($_POST['frpmt_export'])){nocache_headers();header('Content-Type: application/json; charset=utf-8');header('Content-Disposition: attachment; filename="frpmesh-settings.json"');echo wp_json_encode(array('schema'=>1,'theme'=>'frpmesh-hybrid','settings'=>frpmt_sanitize(frpmt_options())),JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE);exit;}
 if(isset($_POST['frpmt_reset'])){$section=sanitize_key(wp_unslash($_POST['frpmt_reset']));$old=frpmt_options();if($section==='all')$old=array();elseif(array_key_exists($section,frpmt_sections())){foreach(frpmt_schema() as $key=>$field){if($field['section']===$section)unset($old[$key]);}}else wp_die(esc_html__('بخش نامعتبر است.','frpmesh-hybrid'));update_option('frpmt_settings',$old,false);$status='reset';}
 elseif(isset($_POST['frpmt_import'])){$file=isset($_FILES['frpmt_file'])?$_FILES['frpmt_file']:array();if(empty($file['tmp_name'])||!empty($file['error'])||empty($file['size'])||$file['size']>1048576||!is_uploaded_file($file['tmp_name'])){wp_die(esc_html__('فایل JSON معتبر با حداکثر حجم ۱ مگابایت بارگذاری کنید.','frpmesh-hybrid'));}$data=json_decode(file_get_contents($file['tmp_name']),true);if(!is_array($data)||!isset($data['schema'],$data['theme'],$data['settings'])||$data['schema']!==1||$data['theme']!=='frpmesh-hybrid'||!is_array($data['settings'])||array_diff(array_keys($data['settings']),array_keys(frpmt_schema())))wp_die(esc_html__('نسخه یا ساختار فایل معتبر نیست.','frpmesh-hybrid'));update_option('frpmt_settings',frpmt_sanitize($data['settings']),false);$status='imported';}
 else wp_die(esc_html__('درخواست نامعتبر است.','frpmesh-hybrid'));wp_safe_redirect(add_query_arg('frpmt_status',$status,admin_url('admin.php?page=frpmt-settings#'.('reset'===$status?'dashboard':'transfer'))));exit;
}
add_action('admin_post_frpmt_transfer','frpmt_transfer');
