<?php
/** Accessible RTL settings dashboard. */
defined('ABSPATH') || exit;
function frpmt_settings_pages_overview() {
 $names=array('home'=>__('خانه','frpmesh-hybrid'),'about'=>__('درباره ما','frpmesh-hybrid'),'services'=>__('خدمات','frpmesh-hybrid'),'contact'=>__('تماس','frpmesh-hybrid'),'blog'=>__('وبلاگ','frpmesh-hybrid'));
 $known=get_option('frpme_v3_pages',array());if(!is_array($known))$known=array();
 echo '<div class="frpmt-page-list">';foreach($names as $slug=>$label){$id=!empty($known[$slug])&&'page'===get_post_type(absint($known[$slug]))?absint($known[$slug]):0;if(!$id){$existing=get_page_by_path($slug,OBJECT,'page');$id=$existing?absint($existing->ID):0;}
  echo '<div class="frpmt-page-row"><div><strong>'.esc_html($label).'</strong><small>'.esc_html($id?__('برگه موجود','frpmesh-hybrid'):__('هنوز ساخته نشده','frpmesh-hybrid')).'</small></div><div>';
  if($id){echo '<a class="button" href="'.esc_url(get_edit_post_link($id)).'">'.esc_html__('ویرایش برگه','frpmesh-hybrid').'</a> ';if(defined('ELEMENTOR_VERSION'))echo '<a class="button" href="'.esc_url(admin_url('post.php?post='.$id.'&action=elementor')).'">'.esc_html__('ویرایش با المنتور','frpmesh-hybrid').'</a>';}
  else echo '<a class="button" href="'.esc_url(admin_url('post-new.php?post_type=page')).'">'.esc_html__('ساخت برگه','frpmesh-hybrid').'</a>';echo '</div></div>';
 }echo '</div>';
 if(function_exists('frpme_v3_bootstrap'))echo '<p class="frpmt-hint"><a href="'.esc_url(admin_url('admin.php?page=frpme-native-setup')).'">'.esc_html__('راه‌اندازی خودکار صفحه‌های طراحی FRP Mesh','frpmesh-hybrid').'</a></p>';
}
function frpmt_settings_page() {
 if (!current_user_can('edit_theme_options')) { wp_die(esc_html__('دسترسی مجاز نیست.','frpmesh-hybrid')); }
 $sections=frpmt_sections();$theme=wp_get_theme();$logo=absint(frpmt_option('logo_id'))?:absint(get_theme_mod('custom_logo'));
 echo '<div class="wrap frpmt-admin" dir="rtl"><div class="frpmt-app">';
 echo '<header class="frpmt-top"><div class="frpmt-brand">';
 if ($logo) echo wp_get_attachment_image($logo,'thumbnail',false,array('class'=>'frpmt-brand-image','alt'=>''));
 else echo '<span class="frpmt-brand-mark" aria-hidden="true">F</span>';
 echo '<span><strong>'.esc_html__('FRP Mesh','frpmesh-hybrid').'</strong><small>'.esc_html__('مرکز تنظیمات پوسته','frpmesh-hybrid').' · v'.esc_html($theme->get('Version')).'</small></span></div>';
 echo '<div class="frpmt-top-actions"><div class="frpmt-search-wrap"><label for="frpmt-search" class="screen-reader-text">'.esc_html__('جستجوی تنظیمات','frpmesh-hybrid').'</label><span class="frpmt-search-icon" aria-hidden="true">⌕</span><input id="frpmt-search" type="search" role="combobox" aria-controls="frpmt-results" aria-expanded="false" aria-autocomplete="list" placeholder="'.esc_attr__('جستجو؛ مثلاً لوگو، رنگ، موبایل…','frpmesh-hybrid').'" autocomplete="off"><div id="frpmt-results" class="frpmt-results" role="listbox" hidden></div></div><span id="frpmt-dirty" role="status" hidden>'.esc_html__('● تغییرات ذخیره‌نشده','frpmesh-hybrid').'</span><button type="submit" form="frpmt-form" class="button button-primary frpmt-save">'.esc_html__('ذخیره تغییرات','frpmesh-hybrid').'</button></div></header>';
 echo '<div id="frpmt-toast" role="status" aria-live="polite" hidden></div>';
 if (isset($_GET['settings-updated']) && 'true'===sanitize_text_field(wp_unslash($_GET['settings-updated']))) {echo '<div class="notice notice-success is-dismissible"><p>'.esc_html__('تنظیمات ذخیره شد.','frpmesh-hybrid').'</p></div>';}
 $notice=isset($_GET['frpmt_status'])?sanitize_key(wp_unslash($_GET['frpmt_status'])):'';
 if (in_array($notice,array('imported','reset'),true))echo '<div class="notice notice-success is-dismissible"><p>'.esc_html('imported'===$notice?__('تنظیمات وارد شد.','frpmesh-hybrid'):__('تنظیمات بازنشانی شد.','frpmesh-hybrid')).'</p></div>';
 echo '<div class="frpmt-shell"><nav class="frpmt-nav" aria-label="'.esc_attr__('بخش‌های تنظیمات قالب','frpmesh-hybrid').'">';
 $groups=array(__('نمای کلی','frpmesh-hybrid')=>array('dashboard'),__('ظاهر سایت','frpmesh-hybrid')=>array('identity','colors','type','layout','header','footer'),__('محتوا و اتصال‌ها','frpmesh-hybrid')=>array('pages','blog','commerce','seo','performance','advanced'));
 foreach ($groups as $group=>$keys) {echo '<p class="frpmt-nav-label">'.esc_html($group).'</p>';foreach ($keys as $key) {echo '<button type="button" class="frpmt-tab" data-section="'.esc_attr($key).'" aria-controls="frpmt-panel-'.esc_attr($key).'">'.esc_html($sections[$key]).'<span aria-hidden="true">‹</span></button>';}}
 echo '<div class="frpmt-nav-bottom"><button type="button" class="frpmt-tab" data-section="transfer" aria-controls="frpmt-panel-transfer">'.esc_html__('پشتیبان‌گیری و بازنشانی','frpmesh-hybrid').'<span aria-hidden="true">‹</span></button></div></nav><main class="frpmt-panels" id="frpmt-main">';
 echo '<form id="frpmt-form" action="'.esc_url(admin_url('options.php')).'" method="post">';settings_fields('frpmt_group');
 echo '<section class="frpmt-panel" id="frpmt-panel-dashboard" data-section="dashboard" aria-labelledby="frpmt-title-dashboard"><div class="frpmt-intro"><span class="frpmt-eyebrow">'.esc_html__('داشبورد','frpmesh-hybrid').'</span><h2 id="frpmt-title-dashboard">'.esc_html__('قالب خود را از اینجا مدیریت کنید','frpmesh-hybrid').'</h2><p>'.esc_html__('برای ویرایش بصری بخش‌های اصلی، افزونه همراه و در صورت نیاز Elementor را فعال کنید. تنظیمات این صفحه مستقل از Elementor کار می‌کند.','frpmesh-hybrid').'</p></div>';
 $statuses=array(array(__('نسخه پوسته','frpmesh-hybrid'),$theme->get('Version'),true),array(__('وردپرس','frpmesh-hybrid'),get_bloginfo('version'),true),array(__('PHP','frpmesh-hybrid'),PHP_VERSION,true),array(__('Elementor','frpmesh-hybrid'),defined('ELEMENTOR_VERSION')?ELEMENTOR_VERSION:__('نصب نیست','frpmesh-hybrid'),defined('ELEMENTOR_VERSION')),array(__('WooCommerce','frpmesh-hybrid'),defined('WC_VERSION')?WC_VERSION:__('نصب نیست','frpmesh-hybrid'),defined('WC_VERSION')),array(__('افزونه طراحی FRP','frpmesh-hybrid'),defined('FRPME_VERSION')?FRPME_VERSION:__('نصب نیست','frpmesh-hybrid'),defined('FRPME_VERSION')),array(__('افزونه سئو','frpmesh-hybrid'),defined('RANK_MATH_VERSION')?'Rank Math':(defined('WPSEO_VERSION')?'Yoast SEO':__('تشخیص داده نشد','frpmesh-hybrid')),defined('RANK_MATH_VERSION')||defined('WPSEO_VERSION')),array(__('کش','frpmesh-hybrid'),defined('WP_ROCKET_VERSION')?'WP Rocket':(defined('LSCWP_V')?'LiteSpeed Cache':__('تشخیص داده نشد','frpmesh-hybrid')),defined('WP_ROCKET_VERSION')||defined('LSCWP_V')));
 echo '<div class="frpmt-status-grid">';foreach ($statuses as $status)echo '<div class="frpmt-status-card"><span>'.esc_html($status[0]).'</span><strong>'.esc_html($status[1]).'</strong><i class="'.($status[2]?'frpmt-status-on':'frpmt-status-off').'" aria-hidden="true"></i></div>';echo '</div>';
 echo '<div class="frpmt-quick"><h3>'.esc_html__('دسترسی سریع','frpmesh-hybrid').'</h3><div>';foreach (array('identity'=>__('لوگو و هویت','frpmesh-hybrid'),'colors'=>__('رنگ‌ها','frpmesh-hybrid'),'type'=>__('فونت‌ها','frpmesh-hybrid'),'header'=>__('هدر','frpmesh-hybrid'),'transfer'=>__('خروجی تنظیمات','frpmesh-hybrid')) as $section=>$label)echo '<button type="button" class="button" data-jump="'.esc_attr($section).'">'.esc_html($label).'</button>';if(defined('ELEMENTOR_VERSION'))echo '<a class="button" href="'.esc_url(admin_url('admin.php?page=elementor')).'">'.esc_html__('باز کردن Elementor','frpmesh-hybrid').'</a>';echo '</div></div>';
 echo '<div class="frpmt-hint">'.esc_html__('گزینه‌هایی که نشان «اتصال در دست تکمیل» دارند، هنوز ظاهر بخش مربوط را تغییر نمی‌دهند و برای تنظیمات آینده نگهداری می‌شوند.','frpmesh-hybrid').'</div></section>';
 foreach ($sections as $section=>$label) {if('dashboard'===$section)continue;
  echo '<section class="frpmt-panel" id="frpmt-panel-'.esc_attr($section).'" data-section="'.esc_attr($section).'" aria-labelledby="frpmt-title-'.esc_attr($section).'" hidden><div class="frpmt-panel-head"><div><span class="frpmt-eyebrow">'.esc_html__('تنظیمات پوسته','frpmesh-hybrid').'</span><h2 id="frpmt-title-'.esc_attr($section).'">'.esc_html($label).'</h2><p>'.esc_html__('مقادیر خالی، طراحی اصلی را حفظ می‌کنند.','frpmesh-hybrid').'</p></div><button type="submit" class="button frpmt-reset" form="frpmt-transfer" name="frpmt_reset" value="'.esc_attr($section).'">'.esc_html__('بازنشانی این بخش','frpmesh-hybrid').'</button></div>';
  if ('type'===$section)echo '<div class="frpmt-devices" role="group" aria-label="'.esc_attr__('تنظیم نمایشگر','frpmesh-hybrid').'"><button type="button" data-device="desktop" aria-pressed="true">'.esc_html__('رومیزی','frpmesh-hybrid').'</button><button type="button" data-device="tablet" aria-pressed="false">'.esc_html__('تبلت','frpmesh-hybrid').'</button><button type="button" data-device="mobile" aria-pressed="false">'.esc_html__('موبایل','frpmesh-hybrid').'</button></div>';
  if ('advanced'===$section)echo '<details class="frpmt-advanced"><summary>'.esc_html__('تنظیمات پیشرفته','frpmesh-hybrid').'</summary>';
  if('pages'===$section)frpmt_settings_pages_overview();else do_settings_sections('frpmt-'.$section);if ('advanced'===$section)echo '</details>';echo '</section>';
 }
 echo '</form><section class="frpmt-panel" id="frpmt-panel-transfer" data-section="transfer" aria-labelledby="frpmt-title-transfer" hidden><div class="frpmt-panel-head"><div><span class="frpmt-eyebrow">'.esc_html__('مدیریت داده‌ها','frpmesh-hybrid').'</span><h2 id="frpmt-title-transfer">'.esc_html__('پشتیبان‌گیری و بازنشانی','frpmesh-hybrid').'</h2><p>'.esc_html__('پیش از وارد کردن فایل جدید، خروجی تنظیمات فعلی را نگه دارید.','frpmesh-hybrid').'</p></div></div>';
 echo '<form id="frpmt-transfer" action="'.esc_url(admin_url('admin-post.php')).'" method="post" enctype="multipart/form-data"><input type="hidden" name="action" value="frpmt_transfer">';wp_nonce_field('frpmt_transfer');
 echo '<div class="frpmt-transfer-grid"><div class="frpmt-transfer-card"><h3>'.esc_html__('دریافت نسخهٔ پشتیبان','frpmesh-hybrid').'</h3><p>'.esc_html__('یک فایل JSON از تنظیمات فعلی دریافت کنید.','frpmesh-hybrid').'</p><button type="submit" class="button" name="frpmt_export" value="1" formnovalidate>'.esc_html__('دریافت فایل JSON','frpmesh-hybrid').'</button></div><div class="frpmt-transfer-card"><h3>'.esc_html__('درون‌ریزی تنظیمات','frpmesh-hybrid').'</h3><p>'.esc_html__('فقط فایل JSON خروجی همین پوسته، تا ۱ مگابایت، پذیرفته می‌شود.','frpmesh-hybrid').'</p><label for="frpmt-file">'.esc_html__('انتخاب فایل','frpmesh-hybrid').'</label><input type="file" id="frpmt-file" name="frpmt_file" accept="application/json,.json"><button type="submit" class="button" name="frpmt_import" value="1">'.esc_html__('بارگذاری و اعمال','frpmesh-hybrid').'</button></div></div><div class="frpmt-danger"><h3>'.esc_html__('بازگشت به تنظیمات پیش‌فرض','frpmesh-hybrid').'</h3><p>'.esc_html__('فقط تنظیمات این پنل پاک می‌شود؛ محتوای برگه‌ها و تنظیمات افزونه همراه دست‌نخورده می‌ماند.','frpmesh-hybrid').'</p><button type="submit" class="button frpmt-reset" name="frpmt_reset" value="all">'.esc_html__('بازنشانی همه تنظیمات','frpmesh-hybrid').'</button></div></form></section></main></div>';
 echo '<dialog id="frpmt-confirm" aria-labelledby="frpmt-confirm-title" aria-describedby="frpmt-confirm-description"><h2 id="frpmt-confirm-title">'.esc_html__('بازنشانی تنظیمات؟','frpmesh-hybrid').'</h2><p id="frpmt-confirm-description">'.esc_html__('این کار مقدارهای ذخیره‌شده را پاک می‌کند.','frpmesh-hybrid').'</p><div><button type="button" class="button" data-dialog-cancel>'.esc_html__('انصراف','frpmesh-hybrid').'</button><button type="button" class="button button-primary" data-dialog-accept>'.esc_html__('تأیید بازنشانی','frpmesh-hybrid').'</button></div></dialog></div></div>';
}
