<?php
/** Settings API control renderer; no controls are loaded outside this admin screen. */
defined('ABSPATH') || exit;
function frpmt_field($args) {
 $key=$args['key'];$field=$args['field'];$type=$field['type'];$value=frpmt_option($key);
 $id='frpmt_'.$key;$name='frpmt_settings['.$key.']';$attrs=' id="'.esc_attr($id).'" name="'.esc_attr($name).'"';
 $supported=array('logo_id','primary_color','text_color','background_color','border_color','container_width','sticky_header','sticky_background','sticky_shadow','primary_font','body_font','heading_font','custom_css','footer_logo_id','footer_description','footer_copyright','header_cta_text','header_cta_url','header_phone_text','header_cart');
 $connected=in_array($key,$supported,true)||(bool)preg_match('/^(base|h[1-6])_size_(desktop|tablet|mobile)$/',$key)||('color'===$type);
 $device=isset($field['device'])?' data-device="'.esc_attr($field['device']).'"':'';
 echo '<div class="frpmt-control" data-key="'.esc_attr($key).'"'.$device.'>';
 if ('toggle'===$type)echo '<input type="hidden" name="'.esc_attr($name).'" value="0"><label class="frpmt-switch"><input type="checkbox"'.$attrs.' value="1" '.checked($value,1,false).'><span class="frpmt-slider" aria-hidden="true"></span></label>';
 elseif ('select'===$type){echo '<select'.$attrs.'><option value="">'.esc_html__('پیش‌فرض قالب','frpmesh-hybrid').'</option>';foreach(frpmt_choices($key) as $choice=>$label)echo '<option value="'.esc_attr($choice).'" '.selected($value,$choice,false).'>'.esc_html($label).'</option>';echo '</select>';}
 elseif ('media'===$type){echo '<div class="frpmt-media-control"><span class="frpmt-media-preview">';if ($value)echo wp_get_attachment_image(absint($value),'thumbnail',false,array('alt'=>''));else echo '<span class="frpmt-media-empty" aria-hidden="true">▧</span>';echo '</span><div><input type="number" min="0" readonly'.$attrs.' value="'.esc_attr($value).'" aria-label="'.esc_attr($field['label']).'"><button type="button" class="button frpmt-media" data-target="'.esc_attr($id).'">'.esc_html__('انتخاب از کتابخانه رسانه','frpmesh-hybrid').'</button><button type="button" class="button frpmt-clear-media" data-target="'.esc_attr($id).'"'.(!$value?' hidden':'').'>'.esc_html__('حذف تصویر','frpmesh-hybrid').'</button></div></div>';}
 elseif ('color'===$type)echo '<div class="frpmt-color-control"><input type="color" class="frpmt-color" data-target="'.esc_attr($id).'" aria-label="'.esc_attr(sprintf(__('انتخاب رنگ %s','frpmesh-hybrid'),$field['label'])).'" value="'.esc_attr($value?:'#ffffff').'"><input type="text" pattern="#[0-9a-fA-F]{6}"'.$attrs.' value="'.esc_attr($value).'" placeholder="#2563eb" spellcheck="false" dir="ltr"><span class="frpmt-color-swatch" aria-hidden="true" style="--frpmt-swatch:'.esc_attr($value?:'#ffffff').'"></span></div>';
 elseif ('urls'===$type){echo '<div class="frpmt-repeater"><div class="frpmt-repeater-items">';$lines=array_filter(array_map('trim',explode("\n",(string)$value)));if(!$lines)$lines=array('');foreach($lines as $line)echo '<div class="frpmt-repeater-item"><input type="url" value="'.esc_attr($line).'" placeholder="https://" aria-label="'.esc_attr__('آدرس شبکه اجتماعی','frpmesh-hybrid').'"><button type="button" class="button frpmt-repeater-remove" aria-label="'.esc_attr__('حذف پیوند','frpmesh-hybrid').'">×</button></div>';echo '</div><textarea class="frpmt-repeater-value"'.$attrs.' hidden>'.esc_textarea($value).'</textarea><button type="button" class="button frpmt-repeater-add">'.esc_html__('افزودن پیوند','frpmesh-hybrid').'</button></div>';}
 elseif ('css'===$type)echo '<textarea rows="5"'.$attrs.'>'.esc_textarea($value).'</textarea>';
 elseif ('number'===$type){echo '<div class="frpmt-number"><input type="number" min="0" max="2500"'.$attrs.' value="'.esc_attr($value).'">';if(in_array($key,array('container_width','site_width','header_logo_width','border_radius','section_spacing'),true))echo '<input type="range" class="frpmt-range" min="0" max="2500" step="1" data-target="'.esc_attr($id).'" value="'.esc_attr($value!==''?$value:0).'" aria-label="'.esc_attr($field['label']).'">';echo '</div>';}
 else echo '<input type="'.('decimal'===$type?'number':('url'===$type?'url':'text')).'"'.('decimal'===$type?' step="0.01"':'').$attrs.' value="'.esc_attr($value).'">';
 if (!$connected)echo '<small class="frpmt-field-note">'.esc_html__('اتصال به طرح در دست تکمیل؛ مقدار فعلاً ذخیره می‌شود.','frpmesh-hybrid').'</small>';
 elseif('color'===$type)echo '<small class="frpmt-field-note">'.esc_html__('خالی بگذارید تا رنگ اصلی طرح حفظ شود.','frpmesh-hybrid').'</small>';
 elseif(in_array($key,array('footer_logo_id','footer_description','footer_copyright','header_cta_text','header_cta_url','header_phone_text','header_cart'),true))echo '<small class="frpmt-field-note">'.esc_html__('برای هدر و فوتر پایهٔ پوسته؛ طراحی افزونه همراه تنظیمات خودش را دارد.','frpmesh-hybrid').'</small>';
 echo '</div>';
}
