<?php
defined('ABSPATH') || exit;
class Frpme_Field_Widget extends \Elementor\Widget_Base {
 public function get_name(){return 'frpme-field';}public function get_title(){return 'FRP / فیلد تعاملی';}public function get_icon(){return 'eicon-form-horizontal';}public function get_categories(){return array('frpme');}public function get_script_depends(){return array('frpme-runtime');}
 protected function register_controls(){
  $this->start_controls_section('field',array('label'=>esc_html__('محتوای فیلد','frpmesh-editor')));
  $this->add_control('field_type',array('type'=>\Elementor\Controls_Manager::SELECT,'label'=>esc_html__('نوع فیلد','frpmesh-editor'),'options'=>array('text'=>esc_html__('متن','frpmesh-editor'),'number'=>esc_html__('عدد','frpmesh-editor'),'checkbox'=>esc_html__('چک‌باکس','frpmesh-editor'),'range'=>esc_html__('اسلایدر','frpmesh-editor'),'search'=>esc_html__('جستجو','frpmesh-editor'),'textarea'=>esc_html__('متن چندخطی','frpmesh-editor'),'select'=>esc_html__('فهرست','frpmesh-editor'),'progress'=>esc_html__('پیشرفت','frpmesh-editor'),'output'=>esc_html__('خروجی','frpmesh-editor')),'default'=>'text'));
  $controls=array('field_id'=>array(esc_html__('شناسه HTML','frpmesh-editor'),array()),'name'=>array(esc_html__('نام فیلد','frpmesh-editor'),array()),'placeholder'=>array(esc_html__('متن راهنما','frpmesh-editor'),array('field_type'=>array('text','number','search','textarea'))),'value'=>array(esc_html__('مقدار اولیه','frpmesh-editor'),array()),'min'=>array(esc_html__('حداقل','frpmesh-editor'),array('field_type'=>array('number','range','progress'))),'max'=>array(esc_html__('حداکثر','frpmesh-editor'),array('field_type'=>array('number','range','progress'))),'step'=>array(esc_html__('گام','frpmesh-editor'),array('field_type'=>array('number','range'))));
  foreach($controls as $key=>$details){$options=array('label'=>$details[0],'type'=>\Elementor\Controls_Manager::TEXT);if($details[1])$options['condition']=$details[1];if('field_id'===$key)$options['description']=esc_html__('شناسه‌های موردنیاز انیمیشن یا اسکریپت طرح را حفظ کنید.','frpmesh-editor');$this->add_control($key,$options);}
  $this->add_control('required',array('label'=>esc_html__('الزامی','frpmesh-editor'),'type'=>\Elementor\Controls_Manager::SWITCHER,'condition'=>array('field_type'=>array('text','number','search','textarea','select','checkbox'))));
  $this->add_control('options',array('label'=>esc_html__('گزینه‌ها','frpmesh-editor'),'description'=>esc_html__('هر سطر: مقدار|عنوان','frpmesh-editor'),'type'=>\Elementor\Controls_Manager::TEXTAREA,'condition'=>array('field_type'=>'select')));
  $this->end_controls_section();
  $this->start_controls_section('field_style',array('label'=>esc_html__('ظاهر فیلد','frpmesh-editor'),'tab'=>\Elementor\Controls_Manager::TAB_STYLE));
  foreach(array('color'=>esc_html__('رنگ متن','frpmesh-editor'),'background'=>esc_html__('پس‌زمینه','frpmesh-editor')) as $property=>$label)$this->add_control($property,array('label'=>$label,'type'=>\Elementor\Controls_Manager::COLOR,'selectors'=>array('{{WRAPPER}} .frpme-native-node'=>$property.':{{VALUE}}')));
  $this->add_group_control(\Elementor\Group_Control_Typography::get_type(),array('name'=>'field_typography','selector'=>'{{WRAPPER}} .frpme-native-node'));
  $this->end_controls_section();
 }
 protected function render(){$s=$this->get_settings_for_display();$m=frpme_native_meta($this);$a=$m?$m['attrs']:array();$type=in_array($s['field_type'],array('text','number','checkbox','range','search','textarea','select','progress','output'),true)?$s['field_type']:'text';$tag=in_array($type,array('textarea','select','progress','output'),true)?$type:'input';foreach(array('field_id'=>'id','name'=>'name','placeholder'=>'placeholder','min'=>'min','max'=>'max','step'=>'step') as $k=>$attr){if(isset($s[$k])&&''!==$s[$k])$a[$attr]=$s[$k];}if(!empty($s['required'])){$a['required']='required';}else{unset($a['required']);}$v=isset($s['value'])?$s['value']:'';$inner='';if('input'===$tag){$a['type']=$type;$a['value']=$v;}elseif('progress'===$tag){$a['value']=$v;}elseif('select'===$tag){foreach(explode("\n",isset($s['options'])?$s['options']:'') as $row){if(''===trim($row))continue;$parts=explode('|',$row,2);$inner.='<option value="'.esc_attr($parts[0]).'"'.selected($v,$parts[0],false).'>'.esc_html(isset($parts[1])?$parts[1]:$parts[0]).'</option>';}}else{$inner=esc_html($v);}echo '<'.$tag.frpme_native_attrs($a).'>';if('input'!==$tag)echo $inner.'</'.$tag.'>';}
}
class Frpme_Data_Widget extends \Elementor\Widget_Base {
 protected function is_dynamic_content(): bool {return true;}
 public function get_name(){return 'frpme-data';}public function get_title(){return 'FRP / داده وردپرس';}public function get_icon(){return 'eicon-post-list';}public function get_categories(){return array('frpme');}
 protected function register_controls(){
  $this->start_controls_section('data',array('label'=>esc_html__('محتوای وردپرس','frpmesh-editor')));
  $this->add_control('kind',array('label'=>esc_html__('نوع داده','frpmesh-editor'),'type'=>\Elementor\Controls_Manager::SELECT,'options'=>array('menu'=>esc_html__('فهرست سایت','frpmesh-editor'),'home-posts'=>esc_html__('نوشته‌های صفحه خانه','frpmesh-editor'),'blog-filters'=>esc_html__('فیلتر دسته‌ها','frpmesh-editor'),'blog-cards'=>esc_html__('کارت‌های وبلاگ','frpmesh-editor'),'post-title'=>esc_html__('عنوان نوشته','frpmesh-editor'),'post-excerpt'=>esc_html__('خلاصه نوشته','frpmesh-editor'),'post-category'=>esc_html__('دسته نوشته','frpmesh-editor'),'post-meta'=>esc_html__('تاریخ و نویسنده','frpmesh-editor'),'post-content'=>esc_html__('متن نوشته','frpmesh-editor'),'related-posts'=>esc_html__('نوشته‌های مرتبط','frpmesh-editor')),'default'=>'blog-cards'));
  $this->add_control('frpme_post_count',array('label'=>esc_html__('تعداد نوشته‌ها','frpmesh-editor'),'description'=>esc_html__('در آرشیو، تعداد نمایش از تنظیمات خواندن وردپرس گرفته می‌شود.','frpmesh-editor'),'type'=>\Elementor\Controls_Manager::NUMBER,'default'=>6,'min'=>1,'max'=>48,'condition'=>array('kind'=>array('home-posts','blog-cards','related-posts'))));
  $this->end_controls_section();
 }
 protected function render(){$s=$this->get_settings_for_display();$k=$s['kind'];if(!in_array($k,array('menu','home-posts','blog-filters','blog-cards','post-title','post-excerpt','post-category','post-meta','post-content','related-posts'),true))return;$m=frpme_native_meta($this);$t=$m?$m['tag']:'div';$a=$m?$m['attrs']:array();if('span'===$t&&in_array($k,array('menu','home-posts','blog-cards','blog-filters','post-content','related-posts'),true)){$t='div';$a['class']='frpme-data-fragment';}echo '<'.$t.frpme_native_attrs($a).'>'.frpme_dynamic($k,'native',$s).'</'.$t.'>';}
}
